### ISSUE TITLE
doomemacs sis-global-cursor-color-mode nil设置的情况下 切换一次输入法输入中文 然后光标颜色被修改了

### ISSUE THREAD

**Issue by pluswu** [laishulu/emacs-smart-input-source#40]
RT

**Comment by laishulu** [comment]
- If you invoke the mode command directly with no prefix argument (either via M-x, or by binding it to a key and typing that key; see Key Bindings), that toggles the minor mode. The minor mode is turned on if it was off, and turned off if it was on.
- If you invoke the mode command with a prefix argument, the minor mode is unconditionally turned off if that argument is zero or negative; otherwise, it is unconditionally turned on.
- If the mode command is called via Lisp, the minor mode is unconditionally turned on if the argument is omitted or nil. This makes it easy to turn on a minor mode from a major mode's mode hook (see Major Modes). A non-nil argument is handled like an interactive prefix argument, as described above.

你是不是 `(sis-global-cursor-color-mode nil)` 了？
这是错误的disable minor mode的方式，见上面的第三条。
不想enable那个mode，直接把那一行注释掉就行了。
或者已经打开了，想关闭的话， `(sis-global-cursor-color-mode -1)`

**Comment by laishulu** [comment]
上面我说的，是所有minor mode都需要这么用。
并不特定于sis。
